services:
  kafka:
    container_name: kafka
    image: quay.io/ccxdev/kafka-no-zk:latest
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_CREATE_TOPICS=proxy_check:16:1,check_result:2:1
